/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Connection.Conn;
import Helper.UserRole;
import Helper.UserSession;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;


/**
 *
 * @author rajas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPsw = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        cbRole = new javax.swing.JComboBox<>();
        lblPsw1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email ");

        lblPsw.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblPsw.setForeground(new java.awt.Color(255, 255, 255));
        lblPsw.setText("Password ");

        psw.setText("jPasswordField1");

        btnSignup.setText("Sign Up");
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Tutor", "Admin" }));

        lblPsw1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPsw1.setForeground(new java.awt.Color(255, 255, 255));
        lblPsw1.setText("Role ");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPsw)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPsw1)
                    .addComponent(lblEmail))
                .addGap(149, 149, 149)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblPsw)
                .addGap(18, 18, 18)
                .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblPsw1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 480, 650));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Colonna MT", 1, 72)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");
        jPanel3.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duck.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 220, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 460, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        SignUp sp = new SignUp();
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnSignupMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
       if (btnLogin == evt.getSource()) {
        String email = txtEmail.getText();
        String password = new String(psw.getPassword()); 
        String Role = cbRole.getSelectedItem().toString(); // to get the selected item's string value
        String query = ""; // query string

        // Check the role and prepare the query accordingly
        if ("Student".equals(Role)) {
            query = "SELECT * FROM student WHERE Email = ? AND Password = ?";
        } else if ("Tutor".equals(Role)) {
            query = "SELECT * FROM tutor WHERE Email = ? AND Password = ?";
        } else if ("Admin".equals(Role)) {
            query = "SELECT * FROM admin WHERE Email = ? AND Password = ?";
        } else {
            // Handle unexpected role
            JOptionPane.showMessageDialog(null, "Invalid role selected");
            return;
        }
        if ("Tutor".equals(Role)) {
    Conn c = new Conn();
    int teacherId = c.getTeacherId(email); // getting teacher id with the help of email
    if (teacherId != -1) {
        // Store the teacherId in the userSession
        UserSession.getInstance().setTeacherId(teacherId); 
    } else {
        JOptionPane.showMessageDialog(null, "Failed to retrieve teacher details.");
        return; 
    }
}
        try {
            Conn c = new Conn();
            try (PreparedStatement pstmt = c.getConnection().prepareStatement(query)) {
                pstmt.setString(1, email);
                pstmt.setString(2, password); 
                
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    // Login success
                    JOptionPane.showMessageDialog(null, "Welcome to Course Management System", "Title", JOptionPane.INFORMATION_MESSAGE);

                    
                    // Set the user's role
                    String role = cbRole.getSelectedItem().toString();
                    UserRole.getInstance().setRole(role);
                    UserSession.getInstance().setUserEmail(email);
                    
                     Dashboard ds = new Dashboard();
                      ds.setVisible(true);
                        ds.pack();
                        ds.setLocationRelativeTo(null);
                        ds.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();}
                        else{
                    // Login failed message 
                    JOptionPane.showMessageDialog(null, "Invalid email or password");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Login Failed: An error occurred");
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Login loginFrame = new Login();
            loginFrame.pack(); // Adapt frame size to its content
            loginFrame.setLocationRelativeTo(null); // Center the window
            loginFrame.setVisible(true); // Show the window
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPsw;
    private javax.swing.JLabel lblPsw1;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
