/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.Date;
import java.sql.Connection;
import java.sql.Statement; 
import java.sql.ResultSet; 
import java.sql.PreparedStatement; 
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import Connection.Conn; 
import java.sql.SQLException;


/**
 *
 * @author rajas
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
         populateCoursesComboBox(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        psField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addrField = new javax.swing.JTextField();
        phnoField = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lnameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 56)); // NOI18N
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 260, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));
        getContentPane().add(fnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 220, 30));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone Number :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        psField.setText("jPasswordField1");
        getContentPane().add(psField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Date of Birth:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));
        getContentPane().add(addrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 220, 30));
        getContentPane().add(phnoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 220, 30));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Tutor", "Admin" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Role :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 188, 45));

        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 188, 44));
        getContentPane().add(lnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Last Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        lblCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCourse.setText("Course :");
        getContentPane().add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bsc Computer Science", "BIBM", "BCA" }));
        getContentPane().add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 160, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 150, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pexels-henry-&-co-1939485.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 700));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnLoginMouseClicked
 private boolean isValidPhoneNumber(String phoneNumber) {
    // regex pattern for a 10-digit phone number
    String phoneRegex = "^\\d{10}$";

    // Compile the regex pattern
    Pattern pattern = Pattern.compile(phoneRegex);

    // Check if the phoneNumber is null
    if (phoneNumber == null) {
        return false;
    }

    // Match the phoneNumber against the regex pattern
    return pattern.matcher(phoneNumber).matches();
}

    private boolean isValidEmail(String email) {
    // regex pattern for a small lettere and number of  email
    String emailRegex = "^[a-z]+[0-9]+@gmail\\.com$";
    Pattern pattern = Pattern.compile(emailRegex);
    if (email == null) {
        return false;
    }
    return pattern.matcher(email).matches();
}

private boolean isValidPassword(String password) {
    // regex pattern for the password which must contain one Uppercase and number
    String passwordRegex = "^(?=.*[A-Z])(?=.*\\d).+$";


    // Compile the regex pattern
    Pattern pattern = Pattern.compile(passwordRegex);

    // Check if the password is null
    if (password == null) {
        return false;
    }

    // Match the password against the regex pattern
    return pattern.matcher(password).matches();
}


    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
                                      
    if(evt.getSource() == btnCreate){
        try {
            String firstName = fnameField.getText();
            String lastName = lnameField.getText();
            String email = emailField.getText();           
            String password = psField.getText();
            String address = addrField.getText();
            String phoneNumber = phnoField.getText();
            String course = cmbCourse.getSelectedItem().toString(); 
            String role = cmbRole.getSelectedItem().toString();
            Date date = jDateChooser1.getDate();
            java.sql.Date sqlDate = null;
            
            // Validation as per something goes wrong 
            if (date != null) {
                sqlDate = new java.sql.Date(date.getTime());
            }
            
             if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email address.");
            return; 
            }
              if (!isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number.");
            return; 
            }
             if (!isValidPassword(password)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid password.");
            return; 
            }
            String query = ""; 
            String selectedCourse = cmbCourse.getSelectedItem().toString();
            
            // Check the role and prepare the query accordingly
            if ("Student".equals(role)) {
                query = "INSERT INTO student ( Email, Address, PhoneNumber, Password, DateOfBirth, firstname, lastname, course) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?)";
            } else if ("Tutor".equals(role)) {
                query = "INSERT INTO tutor ( Email, Address, PhoneNumber, Password, DateOfBirth, firstname, lastname, course) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?)";
            } else if ("Admin".equals(role)) {
                query = "INSERT INTO admin ( Email, Address, PhoneNumber, Password, DateOfBirth, firstname, lastname) VALUES ( ?, ?, ?, ?, ?, ?, ?)";
            } else {
                // Handling unexpected role
                JOptionPane.showMessageDialog(null, "Invalid role selected");
                return;
            }

            Conn c = new Conn();
            try(PreparedStatement ps = c.getConnection().prepareStatement(query)) {
                ps.setString(1, email);
                ps.setString(2, address);
                ps.setString(3, phoneNumber);
                ps.setString(4, password);
                ps.setDate(5, sqlDate);
                ps.setString(6, firstName);
                ps.setString(7, lastName);
                // if the role is not admin show and insert the course comboBox
                if ("Student".equals(role) || "Tutor".equals(role)){
                    ps.setString(8, course);
                }
                       
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registered Successfully");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for ID and Phone Number");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registration Failed");
            e.printStackTrace();
        }
    }


    }//GEN-LAST:event_btnCreateMouseClicked

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
       // Checking the selected item 
    String selectedItem = (String) cmbRole.getSelectedItem();
    
    // if the role is admin hide the course comboBox
    if ("Admin".equals(selectedItem)) {
        cmbCourse.setVisible(false);
        lblCourse.setVisible(false); 
    } else {
        cmbCourse.setVisible(true);
        lblCourse.setVisible(true); 
    }   
    }//GEN-LAST:event_cmbRoleActionPerformed
private void populateCoursesComboBox() {
    String query = "SELECT name FROM course"; 
    try {
        Conn c = new Conn();
        Connection conn = c.getConnection(); // Get the Connection object from your Conn class
        try (Statement stmt = conn.createStatement()) { 
            ResultSet rs = stmt.executeQuery(query); 
            cmbCourse.removeAllItems(); // Clear existing items
            
            while (rs.next()) {
                String courseName = rs.getString("name"); 
                cmbCourse.addItem(courseName); // Add course name to the combo box
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Failed to populate courses");
        e.printStackTrace();
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrField;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fnameField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField phnoField;
    private javax.swing.JPasswordField psField;
    // End of variables declaration//GEN-END:variables

}
